# https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  codecov: codecov/codecov@5.4.3
  browser-tools: circleci/browser-tools@2.3.1

# https://circleci.com/docs/jobs-steps/#jobs-overview
# https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    # https://circleci.com/docs/executor-intro/
    # https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # https://circleci.com/developer/images/image/cimg/openjdk
      - image: cimg/openjdk:21.0.8

    # https://circleci.com/docs/configuration-reference/#resourceclass
    resource_class: medium

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    # https://circleci.com/docs/jobs-steps/#steps-overview
    # https://circleci.com/docs/configuration-reference/#steps
    steps:
      - browser-tools/install_chrome
      - browser-tools/install_chromedriver
      - checkout
      - run: ./gradlew :core:check
      - run: ./gradlew :core:koverXmlReport
      - codecov/upload:
          files: core/build/reports/kover/report.xml

# https://circleci.com/docs/workflows/
# https://circleci.com/docs/configuration-reference/#workflows
workflows:
  codecov:
    jobs:
      - build
