# https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  codecov: codecov/codecov@5

# https://circleci.com/docs/jobs-steps/#jobs-overview
# https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    # https://circleci.com/docs/executor-intro/
    # https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # https://circleci.com/developer/images/image/cimg/openjdk
      - image: cimg/openjdk:17.0.14

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    # https://circleci.com/docs/jobs-steps/#steps-overview
    # https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: ./gradlew :core:check
      - run: ./gradlew :core:koverXmlReport
      - codecov/upload:
          file: core/build/reports/kover/report.xml

# https://circleci.com/docs/workflows/
# https://circleci.com/docs/configuration-reference/#workflows
workflows:
  codecov:
    jobs:
      - build
