[versions]
# https://github.com/JetBrains/kotlin/releases
kotlin = "2.1.20"
# https://github.com/junit-team/junit5/releases
junit = "5.12.1"
# https://github.com/robfletcher/strikt/releases
strikt = "0.35.1"

[libraries]
# https://junit.org/junit5/docs/current/user-guide/
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
# https://strikt.io/
strikt-core = { module = "io.strikt:strikt-core", version.ref = "strikt" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
